.github/workflows/node.js.yml

Added pipelines

---

junit.xml
package-lock.json
package.json
pull_request_template.md
src/App.test.tsx

Added pull request template

---

.github/workflows/node.js.yml

Fixed pipelines

---

junit.xml
package-lock.json
package.json
src/App.test.tsx
src/App.tsx
src/_shared/i18n/en/index.ts
src/_shared/i18n/index.ts
src/_shared/i18n/it/index.ts
src/_shared/theme/index.ts
src/_shared/theme/style/colors.ts
src/_shared/theme/style/index.ts
src/_shared/types/index.ts
src/_shared/types/paths.ts
src/index.tsx

closes #9
closes #9 
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

Add the initial setup for Chakra, react-router and i18n

---

package-lock.json
package.json
src/App.tsx
src/_shared/theme/components/Button/index.ts
src/_shared/theme/components/Button/sizes.ts
src/_shared/theme/components/Button/variants/index.ts
src/_shared/theme/components/Button/variants/outline.ts
src/_shared/theme/components/Button/variants/outlineSecondary.ts
src/_shared/theme/components/Button/variants/solid.ts
src/_shared/theme/components/Button/variants/solidSecondary.ts
src/_shared/theme/components/index.ts
src/_shared/theme/index.ts
src/_shared/theme/style/borders.ts
src/_shared/theme/style/colors.ts
src/_shared/theme/style/fonts.ts
src/_shared/theme/style/index.ts
src/_shared/theme/style/textStyles.ts

close #18
close #18
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

Set the theme

---

junit.xml
package-lock.json
package.json
src/App.tsx
src/_shared/components/Icon/Icon.test.tsx
src/_shared/store/index.ts
src/_shared/store/reducer.ts
src/_shared/testConfig/TestWrapper.tsx
src/_shared/testConfig/customRender.tsx
src/_shared/testConfig/getStoreForTesting.ts
src/_shared/testConfig/types.ts
src/_shared/utils/formtListToState.test.ts
src/index.tsx
src/player/__tests__/create.test.tsx
src/player/__tests__/fetch.test.tsx
src/setupTests.ts

closes #12
Added custom render and store for testing the reducer and saga. In addition some test have been added.
Secondary addition: 
- Add min coverageThreshold for test

Added custom render, store for testing and test all State

---

src/index.tsx

closes #29
> Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> Also, be sure to always link a work-item, for example: `Closes #1234`;
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
> If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Fixed Index

---

src/_shared/components/PlayerCard/PlayerCard.tsx
src/_shared/components/PlayerFrontCard/PlayerFrontCard.tsx
src/_shared/types/general.ts
src/landing/components/CompanyName/TeamName.tsx
src/landing/components/CompanyName/useTeamName.test.tsx
src/landing/components/CompanyName/useTeamName.tsx
src/landing/components/LandingContext/LandingContext.tsx
src/landing/components/LandingContext/index.ts
src/landing/components/ShowPlayer/useShowPlayer.tsx
src/landing/pages/Landing.tsx

Added useContext to handle team selected in Landing page

---

.eslintrc
.prettierrc

closes #47 
- [] ✅ Lint and unit tests pass locally with my changes

 Added .eslintrc and .prettierrc files

---

src/App.tsx

closes #52
> Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> Also, be sure to always link a work-item, for example: `Closes #1234`;
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

 Added codecov

---

src/App.test.tsx
src/_shared/components/PlayerCard/PlayerCard.tsx
src/builderGame/components/AvailablePlayersColumn/AvailablePlayersColumn.test.tsx
src/builderGame/components/ColumnsContainer/ContainerColumns.test.tsx
src/builderGame/components/ContainerTeams/ContainerTeams.test.tsx
src/builderGame/components/CreateTeamButton/CreateTeamButton.test.tsx
src/builderGame/components/CreateTeamButton/CreateTeamButton.tsx
src/builderGame/components/DraggablePlayer/DraggablePlayer.test.tsx
src/builderGame/components/DraggablePlayer/DraggablePlayer.tsx
src/builderGame/components/DraggablePlayer/DraggablePlayerContent.test.tsx
src/builderGame/components/DraggablePlayer/DraggablePlayerContent.tsx
src/builderGame/components/PlayersList/PlayerList.test.tsx
src/builderGame/components/SelectedPlayerColumn/SelectedPlayerColumn.tsx
src/builderGame/components/Team/Team.test.tsx
src/builderGame/hook/index.ts
src/builderGame/hook/useBuilderGame.test.ts
src/builderGame/hook/useCheckPlayer.ts
src/builderGame/hook/useGetSinglePlayer.ts
src/builderGame/hook/useSelectedPlayers.test.ts
src/builderGame/pages/CreateTeams.test.tsx
src/builderGame/pages/PreMatch.test.tsx
src/builderGame/utils/gameRulesMap.ts
src/landing/components/ShowPlayer/ShowPlayer.test.tsx
src/landing/components/ShowPlayer/useShowPlayer.tsx
src/landing/pages/Landing.test.tsx
src/setupTests.ts

Now the console doens't shows errors when the tests are launched and have async operations
closes #64

 Fix tests to don't display an errors in the console

---

src/builderGame/components/ColumnsContainer/ContainerColumns.test.tsx
src/builderGame/components/ContainerTeams/ContainerTeams.test.tsx
src/builderGame/components/DatePicker/DatePicker.test.tsx
src/builderGame/components/DatePicker/DatePicker.tsx
src/builderGame/components/PlayersList/PlayerList.test.tsx
src/builderGame/components/SelectPlaceAndDateForm/SelectPlaceAndDateForm.tsx
src/builderGame/components/Team/Team.tsx
src/builderGame/hook/useBuilderGame.test.ts
src/builderGame/hook/useBuilderGame.ts
src/builderGame/hook/useSelectedPlayers.test.ts
src/builderGame/pages/CreateTeams.test.tsx
src/builderGame/pages/PreMatch.test.tsx
src/builderGame/store/actions.ts
src/builderGame/store/reducers.ts
src/builderGame/store/rootReducer.ts
src/builderGame/store/selectors.ts
src/builderGame/store/types.ts
src/builderGame/types/general.ts
src/builderGame/utils/formatDate.ts
src/builderGame/utils/index.ts

- Added date and place to store
- Created `useUpdateDateAndPlaceMatch` to update these values
- Fixed the PickDate style 
closes #65

 Created place and date inside builderGame slice

---

src/landing/pages/Landing.tsx

 Deleted wrong component inside Landing page

---

data/db.json
src/_shared/components/PlayerCard/usePlayerCard.tsx
src/_shared/components/PlayerFrontCard/PlayerFrontCard.tsx
src/_shared/components/PlayerFrontCard/useFrontCard.tsx
src/builderGame/components/ContainerTeams/ContainerTeams.tsx
src/builderGame/components/Team/Team.tsx
src/landing/components/LandingLayout/LandingLayout.tsx
src/landing/components/NavBar/NavBar.tsx
src/landing/components/ShowPlayer/useShowPlayer.tsx
src/match/components/MatchDetails/MatchDetails.tsx

- Changed the sizes of PlayerCard component and made it responsive
- Added responsive padding to LandingLayout component
- Changed Team Layout
Preview video:
https://tella.video/refactoring-playercard-and-team-csl5
closes #100

Made responsive the Playercard component and changed Team component layout

---

src/_shared/types/general.ts
src/_shared/types/index.ts
src/builderGame/components/BuilderGameLayout/BuilderGameLayout.test.tsx
src/builderGame/components/ColumnsContainer/ContainerColumns.test.tsx
src/builderGame/components/ContainerTeams/ContainerTeams.test.tsx
src/builderGame/components/PlayersList/PlayerList.test.tsx
src/builderGame/hook/useCheckPathnameAndChosenPlayers.test.ts
src/builderGame/hook/useSelectedPlayers.test.ts
src/builderGame/pages/CreateTeams.test.tsx
src/builderGame/pages/PreMatch.test.tsx
src/builderGame/store/rootReducer.ts
src/builderGame/store/types.ts
src/landing/components/NavBar/NavBar.tsx
src/match/components/MatchDetails/MatchDetails.tsx
src/player/store/types.ts

Created Sport type, added it on BuilderGameState and fixed related tests

---

data/db.json
src/builderGame/components/AddPlayerForm/AddPlayerForm.tsx
src/builderGame/components/AddPlayerForm/useAddPlayerForm.tsx
src/builderGame/components/InputContainer/InputContainer.test.tsx
src/builderGame/components/InputContainer/InputContainer.tsx
src/builderGame/i18n/en/createPlayerModal.ts
src/builderGame/i18n/it/createPlayerModal.ts

UI Preview:
https://tella.video/my-video-g92g
closes #149

Added error messages to each input in AddPlayerForm

---

data/db.json
src/_shared/theme/components/Button/sizes.ts
src/builderGame/hook/useBuilderGame.test.ts
src/builderGame/hook/useBuilderGame.ts
src/builderGame/store/actions.ts
src/builderGame/store/reducers.ts
src/builderGame/store/rootReducer.ts
src/builderGame/store/types.ts
src/match/components/ReplayMatchButton/ReplayMatchButton.test.tsx
src/match/components/ReplayMatchButton/ReplayMatchButton.tsx
src/match/components/ReplayMatchButton/index.ts
src/match/i18n/en/matchInfo.ts
src/match/i18n/it/matchInfo.ts
src/match/pages/MatchInfo.tsx

Added an option to each Match to replay a specific match
Other changes:
- Added all logic to replay a game with the same players and match type
- Added useReplayMatch hook
- Created ReplayMatchButton
UI Preview:
https://tella.video/my-video-5hvj
closes #153

Added an option to each Match to replay a specific match

---

src/builderGame/components/ListCardPlayer/ListCardPlayer.tsx
src/builderGame/hook/useBuilderGame.test.ts
src/builderGame/hook/useBuilderGame.ts
src/builderGame/store/actions.ts
src/builderGame/store/reducers.ts
src/builderGame/store/rootReducer.ts
src/builderGame/store/types.ts

UI Preview: 
https://tella.video/my-video-89d0
closes #168

Created logic to remove a player when it is already selected in CreateTeam page

---

src/_shared/components/Icon/IconLibrary.ts
src/_shared/components/Icon/assets/ArrowDown.svg
src/_shared/components/Icon/assets/ArrowLeft.svg
src/_shared/components/Icon/assets/ArrowRight.svg
src/_shared/components/Icon/assets/ArrowUp.svg
src/_shared/components/Icon/assets/ChevronDown.svg
src/_shared/components/Icon/assets/ChevronRight.svg
src/_shared/components/Icon/assets/ChevronUp.svg
src/_shared/theme/components/Button/variants/solidIcon.ts
src/builderGame/components/BuilderGameLayout/BuilderGameLayout.tsx
src/builderGame/components/CreateTeamButton/CreateTeamButton.tsx
src/builderGame/components/ListCardPlayer/ListCardPlayer.tsx
src/builderGame/components/ListCardPlayer/OptionDropdown.tsx
src/builderGame/components/MatchTypeCard/MatchTypeCard.tsx
src/builderGame/components/SelectedPlayersArea/SelectedPlayersArea.tsx
src/builderGame/i18n/en/createTeam.ts
src/builderGame/i18n/en/index.ts
src/builderGame/i18n/en/matchTypeRules.ts
src/builderGame/i18n/en/playersPage.ts
src/builderGame/i18n/it/createTeam.ts
src/builderGame/i18n/it/index.ts
src/builderGame/i18n/it/matchTypeRules.ts
src/builderGame/i18n/it/playersPage.ts

CreateTeamButton component and added the text of the match rule condition.
Other changes:
- Added some icon (arrow and chevron)
- Fixed translations
UI Preview:
https://tella.video/my-video-7x23
closes #157

Created the new UI to the CreateTeam page

---

src/builderGame/components/AddPlayerForm/AddPlayerForm.tsx
src/builderGame/components/ChangeMatchTypeAlert/ChangeMatchTypeAlert.test.tsx
src/builderGame/components/ChangeMatchTypeAlert/ChangeMatchTypeAlert.tsx
src/builderGame/components/ChangeMatchTypeAlert/index.ts
src/builderGame/components/ChangeMatchTypeButton/ChangeMatchTypeButton.test.tsx
src/builderGame/components/ChangeMatchTypeButton/ChangeMatchTypeButton.tsx
src/builderGame/components/ChangeMatchTypeModal/ChangeMatchTypeCard.tsx
src/builderGame/components/ChangeMatchTypeModal/ChangeMatchTypeModal.test.tsx
src/builderGame/hook/useBuilderGame.test.ts
src/builderGame/hook/useBuilderGame.ts
src/builderGame/i18n/en/changeMatchTypeAlert.ts
src/builderGame/i18n/en/index.ts
src/builderGame/i18n/it/changeMatchTypeAlert.ts
src/builderGame/i18n/it/index.ts
src/builderGame/store/actions.ts
src/builderGame/store/reducers.ts
src/builderGame/store/rootReducer.ts
src/builderGame/store/types.ts

Created ChangeMatchTypeAlert component
Other changes:
- Created changeSelectPlayersLength action to remove the excessive players when the user will change the match types
- Added some test
UI Preview:
https://tella.video/lucas-video-a920
closes #143

Created ChangeMatchTypeAlert component

---

src/App.test.tsx
src/_shared/components/PlayerCard/PlayerCard.tsx
src/_shared/hook/index.ts
src/_shared/hook/useGetRoleList.ts
src/_shared/i18n/en/playerRoles.ts
src/_shared/i18n/it/playerRoles.ts
src/_shared/types/general.ts
src/builderGame/components/AddPlayerForm/AddPlayerForm.tsx
src/builderGame/components/AddPlayerForm/useAddPlayerForm.tsx
src/builderGame/components/ContainerTeams/ContainerTeams.test.tsx
src/builderGame/components/InputContainer/InputContainer.tsx
src/builderGame/components/ListCardPlayer/ListCardPlayer.test.tsx
src/builderGame/components/ListCardPlayer/ListCardPlayerContent.tsx
src/builderGame/components/PlayerFilters/RoleOptions.tsx
src/builderGame/components/PlayersList/PlayerList.test.tsx
src/builderGame/components/Team/Team.test.tsx
src/builderGame/hook/useCheckPlayer.ts
src/builderGame/hook/useSelectedPlayers.test.ts
src/builderGame/i18n/en/createPlayerModal.ts
src/builderGame/i18n/it/createPlayerModal.ts
src/builderGame/pages/CreateTeam.test.tsx
src/builderGame/pages/PreMatch.test.tsx
src/landing/components/ShowPlayer/ShowPlayer.test.tsx
src/landing/components/ShowPlayer/useShowPlayer.test.tsx
src/landing/pages/Landing.test.tsx
src/match/components/MatchCard/MatchCard.test.tsx

Other changes:
- Updated AddPlayerForm component to have a different checkbox to select the new player roles
- Added different functions to validate the role checkbox and handle its errors
- Updated the role filters UI with the new roles
closes #191

Change GoalKeeper type, from boolean to an objects with different roles.

---

src/App.tsx
src/_shared/components/FiltersContext/FiltersContext.tsx
src/_shared/hook/index.ts
src/_shared/hook/useFilter.ts
src/_shared/hook/useGetRatingList.ts
src/_shared/i18n/en/index.ts
src/_shared/i18n/en/playerFilter.ts
src/_shared/i18n/en/playerRatings.ts
src/_shared/i18n/it/index.ts
src/_shared/i18n/it/playerFilter.ts
src/_shared/i18n/it/playerRatings.ts
src/_shared/theme/components/Tag.ts
src/_shared/theme/index.ts
src/builderGame/components/ActiveFilterTags/FilterTag.test.tsx
src/builderGame/components/ActiveFilterTags/FilterTag.tsx
src/builderGame/components/ActiveFilterTags/FilterTagList.tsx
src/builderGame/components/ActiveFilterTags/index.ts
src/builderGame/components/AddPlayerForm/AddPlayerForm.tsx
src/builderGame/components/PlayerFilters/PlayerFilters.tsx
src/builderGame/components/PlayerFilters/RatingOptions.tsx
src/builderGame/components/PlayerFilters/RoleOptions.tsx
src/builderGame/i18n/en/createPlayerModal.ts
src/builderGame/i18n/en/index.ts
src/builderGame/i18n/en/playerFilter.ts
src/builderGame/i18n/it/createPlayerModal.ts
src/builderGame/i18n/it/index.ts
src/builderGame/i18n/it/playerFilter.ts

Added the FilterTag and FilterTagList components and Filter
Other changes:
- Added several functions to add and remove filters
- Added some translations
- Changed RatingOptions component, now it has a checkbox group to select multiple ratings
closes #198

Added the FilterTag and FilterTagList components
